title: Блог на Эво 3
description: Как создать крутой блог на Evo CMS за полчаса (тут работы на полчаса).
baseurl: "/just-the-docs" # repo folder
theme: just-the-docs

url: https://aharito.github.io
repository: aharito/just-the-docs # for github-metadata

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
