title: Создание блога на Evolution CMS 3
description: Как создать крутой блог на Evo CMS за полчаса (тут работы на полчаса).
theme: just-the-docs

url: https://aharito.github.io/just-the-docs

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
